### ISSUE TITLE
Cyrillic dont work

### ISSUE THREAD

**Issue by saskop** [mt-support/tribe-ext-pdf-tickets#3]
Cyrillic text not displaying correctly

**Comment by cliffordp** [comment]
Hi. See this in [the changelog](https://theeventscalendar.com/extensions/pdf-tickets/) from version 1.1.0:

> Tweak – Added new `tribe_ext_pdf_tickets_mpdf_args` filter to customize the arguments sent to [mPDF](https://github.com/mpdf/mpdf)
